server:
  port: 8001

spring:
  redis:
    host: 172.17.0.1
    port: 6379
    password: root
    database: 1
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 10000

  datasource:
    url: jdbc:mysql://114.116.103.22:3306/jd
    username: jingdian
    password: Jingdian_1997
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    time-zone: GMT+8
    date-format: java.text.SimpleDateFormat

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.jd.graduation.mapper