server:
  port: 8080

spring:
  redis:
    host: 122.112.244.157
    port: 6379
    password: root
    database: 0

  datasource:
    url: jdbc:mysql://114.116.103.22:3306/jingdian
    username: jingdian
    password: Jingdian_1997
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.jd.graduation.mapper